apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-service
  template:
    metadata:
      labels:
        app: events-service
    spec:
      containers:
      - name: events-service
        image: ghcr.io/<your-username>/events-service:latest
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: cinemaabyss-config

---
apiVersion: v1
kind: Service
metadata:
  name: events-service
spec:
  selector:
    app: events-service
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
