apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: proxy-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.proxyService.replicas }}
  selector:
    matchLabels:
      app: proxy-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
      containers:
        - name: proxy-service
          image: "{{ .Values.proxyService.image.repository }}:{{ .Values.proxyService.image.tag }}"
          imagePullPolicy: {{ .Values.proxyService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.proxyService.service.targetPort }}
          envFrom:
            - configMapRef:
                name: cinemaabyss-config
          env:
            - name: PORT
              value: "{{ .Values.proxyService.service.targetPort }}"
            - name: MONOLITH_URL
              value: "{{ .Values.config.monolithUrl | default "http://monolith:8080" }}"
            - name: MOVIES_SERVICE_URL
              value: "{{ .Values.config.moviesServiceUrl | default "http://movies-service:8081" }}"
            - name: EVENTS_SERVICE_URL
              value: "{{ .Values.config.eventsServiceUrl | default "http://events-service:8082" }}"
            - name: GRADUAL_MIGRATION
              value: "{{ .Values.config.gradualMigration | default "true" }}"
            - name: MOVIES_MIGRATION_PERCENT
              value: "{{ .Values.config.moviesMigrationPercent | default "100" }}"
          resources:
{{ toYaml .Values.proxyService.resources | indent 12 }}
      {{- if .Values.imagePullSecrets.name }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: proxy-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: proxy-service
  ports:
    - protocol: TCP
      port: {{ .Values.proxyService.service.port }}
      targetPort: {{ .Values.proxyService.service.targetPort }}
  type: {{ .Values.proxyService.service.type }}
